name: Master
on:
  push:
    branches:
      - schedule/github-workflow-cron-job
  schedule:
    - cron: '50 20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running!"
